# Ultralytics YOLO 🚀, GPL-3.0 license

site_name: YOLOv8 Docs
repo_url: https://github.com/ultralytics/ultralytics
edit_uri: https://github.com/ultralytics/ultralytics/tree/main/docs
repo_name: ultralytics/ultralytics
remote_name: https://github.com/ultralytics/docs

theme:
  name: "material"
  logo: https://github.com/ultralytics/assets/raw/main/logo/Ultralytics_Logotype_Reverse.svg
  favicon: https://github.com/ultralytics/assets/raw/main/logo/favicon-yolo.ico
  font:
    text: Roboto

  palette:
    # Palette toggle for light mode
    - scheme: default
      # primary: grey
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      # primary: black
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - content.action.edit
    - content.code.annotate
    - content.tooltips
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    - navigation.top
    - navigation.expand
    - navigation.footer
    - navigation.tracking
    - navigation.instant
    - navigation.indexes
    - content.tabs.link  # all code tabs change simultaneously

# Customization
copyright: Ultralytics 2023. All rights reserved.
extra:
  # version:
  #   provider: mike  #  version drop-down menu
  analytics:
    provider: google
    property: G-2M5EHKC0BH
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/heart
          name: This page was helpful
          data: 1
          note: Thanks for your feedback!
        - icon: material/heart-broken
          name: This page could be improved
          data: 0
          note: >-
            Thanks for your feedback!<br>
            <a href="https://github.com/ultralytics/ultralytics/issues/new?title=Docs+Feedback+for+{title}+page+at+{url}&labels=enhancement&template=feature-request.yml" target="_blank" rel="noopener">Tell us what we can improve.</a>

  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ultralytics
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/ultralytics/
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/ultralytics
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/ultralytics
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/r/ultralytics/ultralytics/
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/ultralytics/

extra_css:
  - stylesheets/style.css

markdown_extensions:
  # Div text decorators
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - tables
  - attr_list
  - def_list
  # Syntax highlight
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets

  # Button
  - attr_list

  # Content tabs
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

  # Highlight
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde

plugins:
  - mkdocstrings
  - search

# Primary navigation
nav:
  - Home: index.md
  - Quickstart: quickstart.md
  - Modes:
      - modes/index.md
      - Train: modes/train.md
      - Val: modes/val.md
      - Predict: modes/predict.md
      - Export: modes/export.md
      - Track: modes/track.md
      - Benchmark: modes/benchmark.md
  - Tasks:
      - tasks/index.md
      - Detect: tasks/detect.md
      - Segment: tasks/segment.md
      - Classify: tasks/classify.md
#      - Keypoints: tasks/keypoints.md
  - Usage:
      - CLI: usage/cli.md
      - Python: usage/python.md
      - Callbacks: usage/callbacks.md
      - Configuration: usage/cfg.md
      - Advanced Customization: usage/engine.md
  - Ultralytics HUB: hub.md
  - iOS and Android App: app.md
  - Reference:
      - Engine:
          - Model: reference/model.md
          - Trainer: reference/base_trainer.md
          - Validator: reference/base_val.md
          - Predictor: reference/base_pred.md
          - Exporter: reference/exporter.md
          - Results: reference/results.md
      - ultralytics.nn: reference/nn.md
      - Operations: reference/ops.md
  - Security: SECURITY.md
