# Path to data
DATA_PATH: "/media/farm/ssd_1_tb_evo_sumsung/ODRC_project/user_datasets/detection/Aerial_Maritime"
DATASET: "VOC"


SPLIT_TRAIN_VALUE: 0.6
SPLIT_VAL_VALUE: 0.35
SPLIT_TEST_VALUE: 0.05
# Path to file with class name

CLASSES: "classes_aeral.txt"

IMG_SIZE: "640"
BATCH_SIZE: "50"
EPOCHS: "400"

# This file generated automaticaly
CONFIG_PATH: ""

# Choose model or you can use your model for training
MODEL_PATH: ''
WEIGHTS: ''


GPU_COUNT: 5
SELECT_GPU: "0,1,2,3,4"
