# Path to data
DATA_PATH: "/media/farm/ssd_1_tb_evo_sumsung/ODRC_project/user_datasets/detection/Food"


SPLIT_TRAIN_VALUE: 0.6
SPLIT_VAL_VALUE: 0.35
SPLIT_TEST_VALUE: 0.05
# Path to file with class name

CLASSES: "classes_food.txt"

IMG_SIZE: "256 256"
BATCH_SIZE: "100"
EPOCHS: "300"

# This file generated automaticaly
CONFIG_PATH: "dataset.yaml"

# Path to trainable model
MODEL_PATH: '/media/farm/ssd_1_tb_evo_sumsung/ODRC_project/ODRC/train_utils/train_model/models/yolov7/cfg/training/yolov7x.yaml'

GPU_COUNT: 5
SELECT_GPU: "0,1,2,3,4"
WEIGHTS: ''
