# Path to data
DATA_PATH: "/media/farm/ssd_1_tb_evo_sumsung/ODRC_project/user_datasets/detection/Website_Screenshots"


SPLIT_TRAIN_VALUE: 0.6
SPLIT_VAL_VALUE: 0.35
SPLIT_TEST_VALUE: 0.05
# Path to file with class name

CLASSES: "classes_web.txt"

IMG_SIZE: "640"
BATCH_SIZE: "40"
EPOCHS: "400"

# This file generated automaticaly
CONFIG_PATH: "dataset.yaml"

# Path to trainable model
MODEL_PATH: '/media/farm/ssd_1_tb_evo_sumsung/ODRC_project/ODRC/train_utils/train_model/models/ultralytics/ultralytics/models/v8/yolov8x6.yaml'


GPU_COUNT: 5
SELECT_GPU: "0,1,2,3,4"
WEIGHTS: ''
