wandb_version: 1

weights:
  desc: null
  value: train_models/models/yolov5/yolov5s.pt
cfg:
  desc: null
  value: /media/space/ssd_1_tb_evo_sumsung1/exp-train/ODRS-update/ODRS/src/DL/train_models/models/yolov5/models/yolov5n.yaml
data:
  desc: null
  value: /media/space/ssd_1_tb_evo_sumsung1/exp-train/ODRS-update/ODRS/runs/2024-06-24_13-22-33_yolov5n/dataset.yaml
hyp:
  desc: null
  value:
    lr0: 0.01
    lrf: 0.01
    momentum: 0.937
    weight_decay: 0.0005
    warmup_epochs: 3.0
    warmup_momentum: 0.8
    warmup_bias_lr: 0.1
    box: 0.05
    cls: 0.5
    cls_pw: 1.0
    obj: 1.0
    obj_pw: 1.0
    iou_t: 0.2
    anchor_t: 4.0
    fl_gamma: 0.0
    hsv_h: 0.015
    hsv_s: 0.7
    hsv_v: 0.4
    degrees: 0.0
    translate: 0.1
    scale: 0.5
    shear: 0.0
    perspective: 0.0
    flipud: 0.0
    fliplr: 0.5
    mosaic: 1.0
    mixup: 0.0
    copy_paste: 0.0
epochs:
  desc: null
  value: 1
batch_size:
  desc: null
  value: 20
imgsz:
  desc: null
  value: 300
rect:
  desc: null
  value: false
resume:
  desc: null
  value: false
nosave:
  desc: null
  value: false
noval:
  desc: null
  value: false
noautoanchor:
  desc: null
  value: false
noplots:
  desc: null
  value: false
evolve:
  desc: null
  value: null
bucket:
  desc: null
  value: ''
cache:
  desc: null
  value: null
image_weights:
  desc: null
  value: false
device:
  desc: null
  value: cpu
multi_scale:
  desc: null
  value: false
single_cls:
  desc: null
  value: false
optimizer:
  desc: null
  value: SGD
sync_bn:
  desc: null
  value: false
workers:
  desc: null
  value: 8
project:
  desc: null
  value: /media/space/ssd_1_tb_evo_sumsung1/exp-train/ODRS-update/ODRS/runs/2024-06-24_13-22-33_yolov5n
name:
  desc: null
  value: exp
exist_ok:
  desc: null
  value: false
quad:
  desc: null
  value: false
cos_lr:
  desc: null
  value: false
label_smoothing:
  desc: null
  value: 0.0
patience:
  desc: null
  value: 100
freeze:
  desc: null
  value:
  - 0
save_period:
  desc: null
  value: -1
seed:
  desc: null
  value: 0
local_rank:
  desc: null
  value: -1
entity:
  desc: null
  value: null
upload_dataset:
  desc: null
  value: false
bbox_interval:
  desc: null
  value: -1
artifact_alias:
  desc: null
  value: latest
save_dir:
  desc: null
  value: /media/space/ssd_1_tb_evo_sumsung1/exp-train/ODRS-update/ODRS/runs/2024-06-24_13-22-33_yolov5n/exp
_wandb:
  desc: null
  value:
    python_version: 3.8.10
    cli_version: 0.15.8
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1719224555.346658
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 5
      - 41
      - 53
      - 55
      - 80
      3:
      - 2
      - 16
      - 23
      4: 3.8.10
      5: 0.15.8
      8:
      - 5
