#dataset_path: path to data folder
#classes_path: path to classes.txt
#GPU: True/False
#speed: 1 - 5 if u want max speed choose 5 or u wanna lower speed 1
#accuracy: 1 - 10 if u want max accuracy choose 10 or u wanna lower acc 1


dataset_path: "user_datasets/yolo/Aerial Maritime"
classes_path: "classes.txt"

GPU: True
speed: 1
accuracy: 10

models_array: ["yolov5l", "yolov5m", "yolov5n", "yolov5s", "yolov5x",
               "yolov7x", "yolov7", "yolov7-tiny", "yolov8x6", "yolov8x",
               "yolov8s", "yolov8n", "yolov8m", "faster-rcnn", "ssd"]


