BATCH_SIZE: 10
CLASSES: classes.txt
CONFIG_PATH: dataset.yaml
DATA_PATH: user_datasets/yolo/aeral
EPOCHS: 40
GPU_COUNT: 0
IMG_SIZE: 300
MODEL: yolov5
SELECT_GPU: cpu
SPLIT_TEST_VALUE: 0.05
SPLIT_TRAIN_VALUE: 0.6
SPLIT_VAL_VALUE: 0.35
