# Path to data
DATA_PATH: "/media/farm/ssd_1_tb_evo_sumsung/ODRC_2/ODRS/user_datasets/yolo/Aerial_Maritime"

# parameters for autosplit dataset
SPLIT_TRAIN_VALUE: 0.6
SPLIT_VAL_VALUE: 0.35
SPLIT_TEST_VALUE: 0.05


# Name *.txt file with names classes
CLASSES: "classes.txt"

IMG_SIZE: "510"
BATCH_SIZE: "16"
EPOCHS: "10"

# This file generated automaticaly
CONFIG_PATH: "dataset.yaml"

# NOTE: using only for yolo architecture
#1)YOLOV5: To view models for the yolov5 architecture, use this path: ODRS/ODRS/train_utils/train_model/models/yolov5/models
#2)YOLOV7: To view models for the yolov7 architecture, use this path: ODRS/ODRS/train_utils/train_model/models/yolov7/cfg/training
#3)YOLOV8: To view models for the yolov8 architecture, use this path: ODRS/ODRS/train_utils/train_model/models/ultralytics/ultralytics/models/v8/

MODEL_PATH: '/media/farm/ssd_1_tb_evo_sumsung/ODRC_2/ODRS/ODRS/train_utils/train_model/models/ultralytics/ultralytics/models/v8/yolov8l.yaml'

# NOTE: using only for yolo architecture 
GPU_COUNT: 4
SELECT_GPU: "0,1,2,3"

