BATCH_SIZE: [25, 20]
CLASSES: classes.txt
DATA_PATH: Warp-D
EPOCHS: [4, 5]
GPU_COUNT: 1
IMG_SIZE: [300, 400]
MODEL: [yolov5l, yolov5s]
SELECT_GPU: 0

CONFIG_PATH: dataset.yaml
SPLIT_TRAIN_VALUE: 0.6
SPLIT_VAL_VALUE: 0.35
