BATCH_SIZE: 20
CLASSES: classes.txt
DATA_PATH: /media/space/ssd_1_tb_evo_sumsung/Work/Warp-D
EPOCHS: 2
GPU_COUNT: 1
IMG_SIZE: 300
MODEL: ssd
SELECT_GPU: 0

CONFIG_PATH: dataset.yaml
SPLIT_TRAIN_VALUE: 0.6
SPLIT_VAL_VALUE: 0.35
