name: Ml-test

on:
  push:
    branches: [ "master", "develop"]
  pull_request:
    branches: [ "master" ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: "3.8"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Download dataset
      run: |
        cd user_datasets/yolo
        mkdir plant
        cd plant
        curl -L "https://public.roboflow.com/ds/quiaIDeY6f?key=QszlpRaGoz" > roboflow.zip; unzip roboflow.zip; rm roboflow.zip
    - name: Ml predictions
      run: python ODRS/ml_utils/ml_model_optimizer.py
