name: Model-test

on:
  push:
    branches: [ "master", "develop"]
  pull_request:
    branches: [ "master" ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: "3.8"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Download dataset
      run: |
        cd user_datasets
        git clone https://github.com/AIRI-Institute/WaRP
        mkdir WaRP/Warp-D/valid
        cp -r WaRP/Warp-D/test/* WaRP/Warp-D/valid/
    - name: AI training
      run: |
        python ODRS/train_utils/custom_train_all.py